
const CONFIG={SUPABASE_URL:"https://zabtwhayvkiacytsdqey.supabase.co",SUPABASE_ANON_KEY:"sb_publishable_eLcn2WmkK4AQ0P19UGIwOw_RCOl3Gvm",ADMIN_DEMO_EMAIL:"admin@example.com",ADMIN_DEMO_PASSWORD:"admin123",PASS_PERCENT:70,EXAM_MINUTES:120};
const DEMO_KEY="sap_abap_academy_demo_v1";
const state={user:null,role:null,exam:null,demo:!CONFIG.SUPABASE_URL||!CONFIG.SUPABASE_ANON_KEY,supabase:null};
let db=null;if(!state.demo)db=window.supabase.createClient(CONFIG.SUPABASE_URL,CONFIG.SUPABASE_ANON_KEY);
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
function pct(a,b){return b?Math.round(a/b*100):0}
function demoData(){const r=localStorage.getItem(DEMO_KEY);if(r)return JSON.parse(r);const d={students:[],attempts:[],questions:QUESTIONS};localStorage.setItem(DEMO_KEY,JSON.stringify(d));return d}
function saveDemo(d){localStorage.setItem(DEMO_KEY,JSON.stringify(d))}
function toast(msg,bad=false){const e=document.createElement("div");e.className="notice "+(bad?"error":"");e.style.cssText="position:fixed;right:20px;bottom:20px;z-index:100;max-width:420px";e.textContent=msg;document.body.appendChild(e);setTimeout(()=>e.remove(),3500)}
function shell(content){document.getElementById("app").innerHTML=`<div class="app-shell"><header class="topbar"><div class="brand">SAP <span>ABAP</span> Academy</div><div class="top-actions">${state.user?`<span style="font-size:13px">${esc(state.user.email||"")}</span><button class="btn btn-ghost" onclick="logout()">Logout</button>`:""}</div></header>${content}</div>`}
function renderAuth(){document.getElementById("app").innerHTML=`<div class="auth-wrap"><div class="card auth-card"><div class="brand" style="color:#101828;margin-bottom:18px">SAP <span>ABAP</span> Academy</div><h1>Certification Practice Portal</h1><p class="sub">Student assessment portal with a protected admin area.</p><div class="tabs"><button id="studentTab" class="tab active" onclick="switchAuth('student')">Student Login</button><button id="adminTab" class="tab" onclick="switchAuth('admin')">Admin</button></div><div id="authForm"></div><p class="footer-note">${state.demo?"Demo mode: data is stored in this browser only. Configure Supabase in app.js for shared multi-device use.":"Supabase mode: students use secure email magic links."}</p></div></div>`;switchAuth("student")}
function switchAuth(k){studentTab.classList.toggle("active",k==="student");adminTab.classList.toggle("active",k==="admin");authForm.innerHTML=k==="student"?`<label>Student name</label><input id="studentName" placeholder="e.g. Rahul Sharma"><label>Email address</label><input id="studentEmail" type="email" placeholder="student@example.com"><button class="btn btn-primary full" onclick="studentLogin()">Continue as Student</button>${state.demo?`<div class="notice">Demo mode: no email is sent.</div>`:`<div class="notice">A secure magic link will be sent to the email address.</div>`}`:`<label>Admin email</label><input id="adminEmail" type="email" placeholder="admin@example.com"><label>Admin password</label><input id="adminPassword" type="password" placeholder="Password"><button class="btn btn-primary full" onclick="adminLogin()">Admin Login</button>${state.demo?`<div class="notice">Demo: <b>admin@example.com</b> / <b>admin123</b></div>`:""}`}
async function studentLogin(){const name=studentName.value.trim(),email=studentEmail.value.trim().toLowerCase();if(!name||!email)return toast("Enter name and email.",true);if(state.demo){const d=demoData();let s=d.students.find(x=>x.email===email);if(!s){s={id:crypto.randomUUID(),name,email,created_at:new Date().toISOString()};d.students.push(s)}else s.name=name;saveDemo(d);state.user=s;state.role="student";renderStudent()}else{const{error}=await db.auth.signInWithOtp({email,options:{data:{full_name:name},emailRedirectTo:location.href}});if(error)return toast(error.message,true);toast("Magic link sent. Open it from email to finish login.")}}
async function adminLogin(){const email=adminEmail.value.trim().toLowerCase(),pw=adminPassword.value;if(state.demo){if(email!==CONFIG.ADMIN_DEMO_EMAIL||pw!==CONFIG.ADMIN_DEMO_PASSWORD)return toast("Invalid demo credentials.",true);state.user={email};state.role="admin";renderAdmin()}else{const{data,error}=await db.auth.signInWithPassword({email,password:pw});if(error)return toast(error.message,true);const{data:p}=await db.from("profiles").select("role,full_name,email").eq("id",data.user.id).single();if(p?.role!=="admin"){await db.auth.signOut();return toast("This account is not an admin.",true)}state.user={...data.user,...p};state.role="admin";renderAdmin()}}
async function logout(){if(!state.demo)await db.auth.signOut();state.user=null;state.role=null;state.exam=null;renderAuth()}
function renderStudent(){const d=state.demo?demoData():null,attempts=state.demo?d.attempts.filter(a=>a.student_email===state.user.email):[];shell(`<main class="container"><div class="page-title"><div><h2>Welcome, ${esc(state.user.name||state.user.user_metadata?.full_name||"Student")}</h2><p class="muted">SAP ABAP Certification Practice</p></div></div><div class="grid"><div class="card stat"><div class="label">Questions</div><div class="num">${state.demo?d.questions.length:100}</div></div><div class="card stat"><div class="label">Attempts</div><div class="num">${attempts.length}</div></div><div class="card stat"><div class="label">Best score</div><div class="num">${attempts.length?Math.max(...attempts.map(a=>a.percentage)):"—"}${attempts.length?"%":""}</div></div></div><div class="dashboard-grid" style="margin-top:18px"><div class="card"><h3>Available test</h3><div class="list-item"><div><b>SAP ABAP Certification Mock Test</b><div class="muted">100 questions · ${CONFIG.EXAM_MINUTES} minutes · Pass ${CONFIG.PASS_PERCENT}%</div></div><button class="btn btn-primary" onclick="startExam()">Start Test</button></div></div><div class="card"><h3>Recent attempts</h3>${attempts.length?`<div class="list">${attempts.slice(-5).reverse().map(a=>`<div class="list-item"><div><b>${a.score}/${a.total}</b><div class="muted">${new Date(a.created_at).toLocaleString()}</div></div><span class="badge ${a.percentage>=CONFIG.PASS_PERCENT?"success":"fail"}">${a.percentage}%</span></div>`).join("")}</div>`:`<p class="muted">No attempts yet.</p>`}</div></div></main>`)}
function startExam(){const d=state.demo?demoData():{questions:QUESTIONS};state.exam={questions:[...d.questions].slice(0,100),current:0,answers:{},marked:new Set(),end:Date.now()+CONFIG.EXAM_MINUTES*60000};renderExam()}
function renderExam(){const e=state.exam,q=e.questions[e.current],sel=e.answers[q.id]||"";document.getElementById("app").innerHTML=`<div class="exam-shell"><div class="exam-head"><div><b>SAP ABAP Certification Mock Test</b><div class="muted">Question ${e.current+1} of ${e.questions.length}</div></div><div id="timer" class="timer">--:--</div></div><div class="exam-grid"><div class="card question-card"><div class="q-meta"><span>${esc(q.topic)}</span><span>${e.marked.has(q.id)?"★ Marked for review":""}</span></div><div class="question">${esc(q.question)}</div>${["A","B","C","D"].map(k=>`<label class="option ${sel===k?"selected":""}"><input type="radio" name="answer" ${sel===k?"checked":""} onchange="chooseAnswer('${k}')"><span><b>${k}.</b> ${esc(q.options[k])}</span></label>`).join("")}<div class="exam-nav"><div><button class="btn btn-secondary" onclick="prevQ" ${e.current===0?"disabled":""}>Previous</button> <button class="btn btn-secondary" onclick="markQ()">Mark for review</button></div><div>${e.current===e.questions.length-1?`<button class="btn btn-primary" onclick="submitExam()">Submit Test</button>`:`<button class="btn btn-primary" onclick="nextQ()">Next</button>`}</div></div></div><aside class="card side-card"><h3>Question palette</h3><div class="progress"><div style="width:${pct(Object.keys(e.answers).length,e.questions.length)}%"></div></div><p class="muted">${Object.keys(e.answers).length}/${e.questions.length} answered</p><div class="palette">${e.questions.map((x,i)=>`<button class="pal ${e.answers[x.id]?"answered":""} ${i===e.current?"current":""}" onclick="goQ(${i})">${i+1}</button>`).join("")}</div></aside></div></div>`;updateTimer()}
function chooseAnswer(k){state.exam.answers[state.exam.questions[state.exam.current].id]=k;renderExam()}function nextQ(){if(state.exam.current<state.exam.questions.length-1){state.exam.current++;renderExam()}}function prevQ(){if(state.exam.current>0){state.exam.current--;renderExam()}}function goQ(i){state.exam.current=i;renderExam()}function markQ(){const id=state.exam.questions[state.exam.current].id;state.exam.marked.has(id)?state.exam.marked.delete(id):state.exam.marked.add(id);renderExam()}
let timerHandle=null;function updateTimer(){clearInterval(timerHandle);const tick=()=>{const left=Math.max(0,state.exam.end-Date.now()),s=Math.floor(left/1000),m=Math.floor(s/60),sec=s%60,e=document.getElementById("timer");if(e)e.textContent=`${String(m).padStart(2,"0")}:${String(sec).padStart(2,"0")}`;if(left<=0){clearInterval(timerHandle);submitExam(true)}};tick();timerHandle=setInterval(tick,1000)}
async function submitExam(auto=false){if(!auto&&!confirm("Submit the test now?"))return;clearInterval(timerHandle);const e=state.exam;let score=0;e.questions.forEach(q=>{if(e.answers[q.id]===q.answer)score++});const attempt={id:crypto.randomUUID(),student_id:state.user.id,student_name:state.user.name||state.user.user_metadata?.full_name,student_email:state.user.email,score,total:e.questions.length,percentage:pct(score,e.questions.length),answers:e.answers,created_at:new Date().toISOString()};if(state.demo){const d=demoData();d.attempts.push(attempt);saveDemo(d);state.exam=null;renderResult(attempt)}else{const{error}=await db.from("attempts").insert({student_id:state.user.id,score,total:e.questions.length,percentage:attempt.percentage,answers:e.answers});if(error)return toast(error.message,true);state.exam=null;renderResult(attempt)}}
function renderResult(a){const pass=a.percentage>=CONFIG.PASS_PERCENT;shell(`<main class="container"><div class="card" style="text-align:center;padding:42px"><div class="badge ${pass?"success":"fail"}" style="font-size:15px">${pass?"PASS":"NOT PASSED"}</div><h1 style="font-size:52px;margin:18px 0 4px">${a.percentage}%</h1><p class="muted">${a.score} correct out of ${a.total}</p><div style="max-width:480px;margin:25px auto;text-align:left"><div class="progress"><div style="width:${a.percentage}%"></div></div><p class="muted">Pass mark: ${CONFIG.PASS_PERCENT}%</p></div><button class="btn btn-primary" onclick="reviewAttempt('${a.id}')">Review Answers</button> <button class="btn btn-secondary" onclick="renderStudent()">Dashboard</button></div></main>`)}
function reviewAttempt(id){const d=demoData(),a=d.attempts.find(x=>x.id===id);if(!a)return;shell(`<main class="container"><div class="page-title"><div><h2>Answer Review</h2><p class="muted">${a.score}/${a.total} · ${a.percentage}%</p></div><button class="btn btn-secondary" onclick="renderStudent()">Dashboard</button></div><div class="list">${d.questions.map((q,i)=>{const given=a.answers[q.id]||"—",ok=given===q.answer;return `<div class="card"><b>Q${i+1}. ${esc(q.question)}</b><p>Your answer: <strong>${given==="—"?"Not answered":esc(given+". "+q.options[given])}</strong></p><p>Correct answer: <strong>${q.answer}. ${esc(q.options[q.answer])}</strong></p><p class="muted">${esc(q.explanation)}</p><span class="badge ${ok?"success":"fail"}">${ok?"Correct":"Incorrect"}</span></div>`}).join("")}</div></main>`)}
function renderAdmin(section="overview"){section==="overview"?adminOverview():section==="students"?adminStudents():section==="questions"?adminQuestions():adminResults()}
function adminLayout(inner,section){shell(`<main class="container"><div class="page-title"><div><h2>Admin Dashboard</h2><p class="muted">Manage students, question bank and assessment results</p></div></div><div class="admin-nav">${["overview","students","questions","results"].map(s=>`<button class="btn btn-secondary ${s===section?"active":""}" onclick="renderAdmin('${s}')">${s[0].toUpperCase()+s.slice(1)}</button>`).join("")}</div>${inner}</main>`)}
function adminOverview(){const d=demoData(),avg=d.attempts.length?Math.round(d.attempts.reduce((x,a)=>x+a.percentage,0)/d.attempts.length):0;adminLayout(`<div class="grid"><div class="card stat"><div class="label">Students</div><div class="num">${d.students.length}</div></div><div class="card stat"><div class="label">Questions</div><div class="num">${d.questions.length}</div></div><div class="card stat"><div class="label">Average score</div><div class="num">${avg}%</div></div></div><div class="card" style="margin-top:18px"><h3>Quick actions</h3><button class="btn btn-primary" onclick="renderAdmin('questions')">Manage Question Bank</button> <button class="btn btn-secondary" onclick="renderAdmin('results')">View Results</button></div>`,"overview")}
function adminStudents(){const d=demoData();adminLayout(`<div class="card"><div class="page-title"><h3>Students</h3><span class="muted">${d.students.length} registered</span></div><div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Email</th><th>Registered</th><th>Attempts</th></tr></thead><tbody>${d.students.map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.email)}</td><td>${new Date(s.created_at).toLocaleDateString()}</td><td>${d.attempts.filter(a=>a.student_email===s.email).length}</td></tr>`).join("")||`<tr><td colspan="4" class="muted">No students yet.</td></tr>`}</tbody></table></div></div>`,"students")}
function adminQuestions(){const d=demoData();adminLayout(`<div class="card"><div class="page-title"><div><h3>Question Bank</h3><p class="muted">100 questions based on the supplied ABAP syllabus.</p></div><button class="btn btn-primary" onclick="questionModal()">Add Question</button></div><div class="table-wrap"><table class="table"><thead><tr><th>#</th><th>Topic</th><th>Question</th><th>Answer</th><th>Action</th></tr></thead><tbody>${d.questions.map((q,i)=>`<tr><td>${i+1}</td><td>${esc(q.topic)}</td><td>${esc(q.question)}</td><td><b>${q.answer}</b></td><td><button class="btn btn-secondary" onclick="questionModal(${q.id})">Edit</button> <button class="btn btn-danger" onclick="deleteQuestion(${q.id})">Delete</button></td></tr>`).join("")}</tbody></table></div></div>`,"questions")}
function questionModal(id){const d=demoData(),q=id?d.questions.find(x=>x.id===id):{id:null,topic:"Open SQL",question:"",options:{A:"",B:"",C:"",D:""},answer:"A",explanation:""};const w=document.createElement("div");w.className="modal-backdrop";w.id="qModal";w.innerHTML=`<div class="card modal"><div class="page-title"><h3>${id?"Edit":"Add"} Question</h3><button class="btn btn-secondary" onclick="qModal.remove()">Close</button></div><div class="form-grid"><div><label>Topic</label><input id="qTopic" value="${esc(q.topic)}"></div><div><label>Correct answer</label><select id="qAnswer">${["A","B","C","D"].map(x=>`<option ${q.answer===x?"selected":""}>${x}</option>`).join("")}</select></div><div class="wide"><label>Question</label><textarea id="qText" rows="3">${esc(q.question)}</textarea></div>${["A","B","C","D"].map(x=>`<div><label>Option ${x}</label><input id="q${x}" value="${esc(q.options[x])}"></div>`).join("")}<div class="wide"><label>Explanation</label><textarea id="qExp" rows="3">${esc(q.explanation)}</textarea></div></div><button class="btn btn-primary full" onclick="saveQuestion(${id||"null"})">Save Question</button></div>`;document.body.appendChild(w)}
function saveQuestion(id){const d=demoData(),q={id:id||Date.now(),topic:qTopic.value.trim(),question:qText.value.trim(),options:{A:qA.value.trim(),B:qB.value.trim(),C:qC.value.trim(),D:qD.value.trim()},answer:qAnswer.value,explanation:qExp.value.trim()};if(!q.topic||!q.question||Object.values(q.options).some(x=>!x))return toast("Fill all fields.",true);const i=d.questions.findIndex(x=>x.id===id);if(i>=0)d.questions[i]=q;else d.questions.push(q);saveDemo(d);qModal.remove();adminQuestions()}
function deleteQuestion(id){if(!confirm("Delete this question?"))return;const d=demoData();d.questions=d.questions.filter(q=>q.id!==id);saveDemo(d);adminQuestions()}
function adminResults(){const d=demoData();adminLayout(`<div class="card"><div class="page-title"><h3>Assessment Results</h3><button class="btn btn-secondary" onclick="exportResults()">Export CSV</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Student</th><th>Email</th><th>Score</th><th>%</th><th>Status</th><th>Date</th></tr></thead><tbody>${d.attempts.slice().reverse().map(a=>`<tr><td>${esc(a.student_name)}</td><td>${esc(a.student_email)}</td><td>${a.score}/${a.total}</td><td>${a.percentage}%</td><td><span class="badge ${a.percentage>=CONFIG.PASS_PERCENT?"success":"fail"}">${a.percentage>=CONFIG.PASS_PERCENT?"PASS":"FAIL"}</span></td><td>${new Date(a.created_at).toLocaleString()}</td></tr>`).join("")||`<tr><td colspan="6" class="muted">No attempts yet.</td></tr>`}</tbody></table></div></div>`,"results")}
function exportResults(){const d=demoData(),rows=[["Student","Email","Score","Total","Percentage","Date"],...d.attempts.map(a=>[a.student_name,a.student_email,a.score,a.total,a.percentage,new Date(a.created_at).toISOString()])],csv=rows.map(r=>r.map(x=>`"${String(x??"").replaceAll('"','""')}"`).join(",")).join("\n"),blob=new Blob([csv],{type:"text/csv"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="sap_abap_results.csv";a.click()}
async function boot(){if(!state.demo){const{data}=await db.auth.getSession();if(data.session){const u=data.session.user,{data:p}=await db.from("profiles").select("*").eq("id",u.id).single();state.user={...u,...p};state.role=p?.role||"student";return state.role==="admin"?renderAdmin():renderStudent()}}renderAuth()}boot();
