-- Production exam upgrade. Run once in Supabase SQL Editor after the original supabase.sql.

alter table public.attempts add column if not exists status text not null default 'submitted' check(status in('in_progress','submitted'));
alter table public.attempts add column if not exists started_at timestamptz;
alter table public.attempts add column if not exists expires_at timestamptz;
alter table public.attempts add column if not exists submitted_at timestamptz;

-- The certification exam is one attempt per student, including an attempt that is still in progress.
create unique index if not exists attempts_one_per_student on public.attempts(student_id);

create table if not exists public.exam_events(
 id bigint generated by default as identity primary key,
 attempt_id uuid not null references public.attempts(id) on delete cascade,
 student_id uuid not null references public.profiles(id) on delete cascade,
 event_type text not null,
 metadata jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now());
alter table public.exam_events enable row level security;
drop policy if exists "events own or admin" on public.exam_events;
create policy "events own or admin" on public.exam_events for select to authenticated using(student_id=auth.uid() or public.is_admin());
create policy "events insert own" on public.exam_events for insert to authenticated with check(student_id=auth.uid());

-- Students must not be able to SELECT the questions table directly because that would expose correct_answer.
drop policy if exists "questions read" on public.questions;
create policy "questions admin read" on public.questions for select to authenticated using(public.is_admin());

create or replace function public.start_certification_exam()
returns jsonb language plpgsql security definer set search_path=public
as $$
declare a public.attempts; q jsonb; now_ts timestamptz:=now();
begin
 if auth.uid() is null then raise exception 'Not authenticated'; end if;
 select * into a from public.attempts where student_id=auth.uid() limit 1;
 if found then
   if a.status='in_progress' and a.expires_at > now_ts then
     return public.resume_certification_exam(a.id);
   end if;
   raise exception 'This certification exam has already been attempted and cannot be reattempted.';
 end if;
 insert into public.attempts(student_id,score,total,percentage,answers,status,started_at,expires_at)
 values(auth.uid(),0,100,0,'{}'::jsonb,'in_progress',now_ts,now_ts+interval '180 minutes') returning * into a;
 select jsonb_agg(x.obj order by x.rnd) into q from (
   select jsonb_build_object('id',id,'topic',topic,'question',question,'options',jsonb_build_object('A',option_a,'B',option_b,'C',option_c,'D',option_d)) obj, random() rnd
   from public.questions where active=true order by random() limit 100
 ) x;
 return jsonb_build_object('attempt_id',a.id,'expires_at',a.expires_at,'questions',q,'answers','{}'::jsonb);
end $$;

create or replace function public.resume_certification_exam(p_attempt_id uuid)
returns jsonb language plpgsql security definer set search_path=public
as $$
declare a public.attempts; q jsonb;
begin
 select * into a from public.attempts where id=p_attempt_id and student_id=auth.uid();
 if not found then raise exception 'Attempt not found'; end if;
 if a.status<>'in_progress' then raise exception 'This exam is already submitted'; end if;
 if a.expires_at <= now() then raise exception 'Exam time has expired'; end if;
 select jsonb_agg(x.obj order by x.rnd) into q from (
   select jsonb_build_object('id',id,'topic',topic,'question',question,'options',jsonb_build_object('A',option_a,'B',option_b,'C',option_c,'D',option_d)) obj, random() rnd
   from public.questions where active=true order by random() limit 100
 ) x;
 return jsonb_build_object('attempt_id',a.id,'expires_at',a.expires_at,'questions',q,'answers',a.answers);
end $$;

create or replace function public.save_exam_answer(p_attempt_id uuid,p_question_id bigint,p_answer char(1))
returns void language plpgsql security definer set search_path=public
as $$
declare a public.attempts;
begin
 select * into a from public.attempts where id=p_attempt_id and student_id=auth.uid() for update;
 if not found or a.status<>'in_progress' then raise exception 'Exam is not active'; end if;
 if a.expires_at <= now() then raise exception 'Exam time has expired'; end if;
 if p_answer not in('A','B','C','D') then raise exception 'Invalid answer'; end if;
 update public.attempts set answers=jsonb_set(coalesce(answers,'{}'::jsonb),array[p_question_id::text],to_jsonb(p_answer::text),true) where id=p_attempt_id;
end $$;

create or replace function public.submit_certification_exam(p_attempt_id uuid,p_answers jsonb)
returns jsonb language plpgsql security definer set search_path=public
as $$
declare a public.attempts; s integer:=0; total integer:=0; q record; ans text; pct integer;
begin
 select * into a from public.attempts where id=p_attempt_id and student_id=auth.uid() for update;
 if not found then raise exception 'Attempt not found'; end if;
 if a.status='submitted' then return jsonb_build_object('id',a.id,'score',a.score,'total',a.total,'percentage',a.percentage,'status',a.status); end if;
 select count(*) into total from public.questions where active=true;
 for q in select id,correct_answer from public.questions where active=true limit 100 loop
   ans:=p_answers->>q.id::text; if ans=q.correct_answer then s:=s+1; end if;
 end loop;
 pct:=case when total=0 then 0 else round(s*100.0/least(total,100)) end;
 update public.attempts set answers=p_answers,status='submitted',score=s,total=least(total,100),percentage=pct,submitted_at=now() where id=a.id returning * into a;
 return jsonb_build_object('id',a.id,'score',a.score,'total',a.total,'percentage',a.percentage,'status',a.status);
end $$;

create or replace function public.get_attempt_review(p_attempt_id uuid)
returns jsonb language plpgsql security definer set search_path=public
as $$
declare a public.attempts; r jsonb;
begin
 select * into a from public.attempts where id=p_attempt_id and (student_id=auth.uid() or public.is_admin());
 if not found or a.status<>'submitted' then raise exception 'Attempt not found'; end if;
 select jsonb_agg(jsonb_build_object('id',q.id,'topic',q.topic,'question',q.question,'options',jsonb_build_object('A',q.option_a,'B',q.option_b,'C',q.option_c,'D',q.option_d),'correct_answer',q.correct_answer,'given',a.answers->>q.id::text,'explanation',q.explanation) order by q.id) into r from public.questions q where q.active=true;
 return jsonb_build_object('id',a.id,'score',a.score,'total',a.total,'percentage',a.percentage,'review',coalesce(r,'[]'::jsonb));
end $$;

grant execute on function public.start_certification_exam() to authenticated;
grant execute on function public.resume_certification_exam(uuid) to authenticated;
grant execute on function public.save_exam_answer(uuid,bigint,char) to authenticated;
grant execute on function public.submit_certification_exam(uuid,jsonb) to authenticated;
grant execute on function public.get_attempt_review(uuid) to authenticated;
create or replace function public.log_exam_event(p_attempt_id uuid,p_event_type text,p_metadata jsonb default '{}'::jsonb)
returns void language plpgsql security definer set search_path=public
as $$
begin
 insert into public.exam_events(attempt_id,student_id,event_type,metadata)
 select id,student_id,p_event_type,coalesce(p_metadata,'{}'::jsonb) from public.attempts
 where id=p_attempt_id and student_id=auth.uid() and status='in_progress';
end $$;

grant execute on function public.log_exam_event(uuid,text,jsonb) to authenticated;

