
create extension if not exists pgcrypto;

create table if not exists public.profiles(
 id uuid primary key references auth.users(id) on delete cascade,
 full_name text not null default '', email text not null default '',
 role text not null default 'student' check(role in('student','admin')),
 created_at timestamptz not null default now());

create table if not exists public.questions(
 id bigint generated by default as identity primary key,
 topic text not null, question text not null,
 option_a text not null, option_b text not null, option_c text not null, option_d text not null,
 correct_answer char(1) not null check(correct_answer in('A','B','C','D')),
 explanation text not null default '', active boolean not null default true,
 created_at timestamptz not null default now());

create table if not exists public.attempts(
 id uuid primary key default gen_random_uuid(),
 student_id uuid not null references public.profiles(id) on delete cascade,
 score integer not null,total integer not null,percentage integer not null,
 answers jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());

alter table public.profiles enable row level security;
alter table public.questions enable row level security;
alter table public.attempts enable row level security;

create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin'); $$;

create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path=public
as $$ begin
 insert into public.profiles(id,full_name,email)
 values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),new.email)
 on conflict(id) do update set full_name=excluded.full_name,email=excluded.email;
 return new; end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

create policy "questions read" on public.questions for select to authenticated
using(active=true or public.is_admin());
create policy "questions admin insert" on public.questions for insert to authenticated
with check(public.is_admin());
create policy "questions admin update" on public.questions for update to authenticated
using(public.is_admin()) with check(public.is_admin());
create policy "questions admin delete" on public.questions for delete to authenticated
using(public.is_admin());

create policy "profiles self or admin" on public.profiles for select to authenticated
using(id=auth.uid() or public.is_admin());

create policy "attempts insert own" on public.attempts for insert to authenticated
with check(student_id=auth.uid());
create policy "attempts read own or admin" on public.attempts for select to authenticated
using(student_id=auth.uid() or public.is_admin());
create policy "attempts admin manage" on public.attempts for all to authenticated
using(public.is_admin()) with check(public.is_admin());

-- After creating the admin user in Supabase Authentication, promote it:
-- update public.profiles set role='admin' where email='YOUR_ADMIN_EMAIL';
